name: ar_types
channels:
  - conda-forge
  - defaults  
dependencies:
  - python=3.7
  - pip
 # Core scientific packages
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - netcdf4
  - xarray=0.16.1
  - dask
  - bottleneck
  - metpy=0.12
 # Plotting
  - matplotlib
  - cartopy
  - seaborn=0.11.0
  - cmocean
  - rockhound
 # Jupyter
  - jupyter
  - ipykernel
  - jupyter-server-proxy
 # pip packages
  - pip:
    - jupyterthemes
    - latextable
    - pymannkendall


      
